main = "dist/main.js"
name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[vars]
CUSTOM_DOMAIN = "667725.xyz"

[env.vars]
CUSTOM_DOMAIN = "667725.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "667725.xyz"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.667725.xyz", custom_domain = true },
  { pattern = "quay.667725.xyz", custom_domain = true },
  { pattern = "gcr.667725.xyz", custom_domain = true },
  { pattern = "k8s-gcr.667725.xyz", custom_domain = true },
  { pattern = "k8s.667725.xyz", custom_domain = true },
  { pattern = "ghcr.667725.xyz", custom_domain = true },
  { pattern = "cloudsmith.667725.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.667725.xyz", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
